### ISSUE TITLE
Marketing link

### ISSUE THREAD

**Issue by nkrusch** [the-au-forml-lab/au_ccs_letterhead_template#1]
AU marketing has a box folder of resources, including letterhead templates:  
https://augustauniversity.app.box.com/v/brand-templates/folder/131877841597

Box has an option to add a link to some URL in a box folder. 

There should be a link from the AU letterheads box-directory to this repository.

**Comment by aubertc** [comment]
Done ;-) 
![Screenshot_20240809_115144](https://github.com/user-attachments/assets/e0a6c372-421c-4672-b454-05d7d2c411e4)
