### ISSUE TITLE
Bad indentation when signature graphic is not present.

### ISSUE THREAD

**Issue by phanukaev** [the-au-forml-lab/au_ccs_letterhead_template#5]
Currently, if the pandoc variable `signature` is set to `""` or absent. the name in the signature gets indented by and additional space. See image:
![signature](https://github.com/the-au-forml-lab/au_ccs_letterhead_template/assets/33177304/80b68aec-54b0-490c-b8f8-14cd9f705d14)

**Comment by aubertc** [comment]
I guess I don't understand how pandoc variables & Latex interact, then…

https://github.com/the-au-forml-lab/au_ccs_letterhead_template/blob/6b459ce5bc5cef07a53969c17ef1264031eb6299/template.tex#L209-L218

**Comment by aubertc** [comment]
Try putting a `%` after `\setkomavar{signature}{ `, maybe?

**Comment by aubertc** [comment]
Thanks. https://github.com/the-au-forml-lab/au_ccs_letterhead_template/pull/6
